package:
  name: my_package
  version: 0.0.1

source:
  path: .

build:
  script: python setup.py install

requirements:
  host:
    - python
    - python-dotenv
    - setuptools
  run:
    - python

test:
  imports:
    - my_package
  source_files:
    - tests/test_my_module.py
  requires:
    - pytest
  commands:
    - pytest tests/